# coding: utf-8


CREATE_OFFER_SUCCESS = {
    'response': {
        'httpStatus': 200,
        'data': {
            'Offer': {
                'hostname_id': None,
                'show_custom_variables': '0',
                'default_payout': '0.00000',
                'show_mail_list': '0',
                'payout_cap': '0.00',
                'percent_payout': None,
                'lifetime_payout_cap': '0.00',
                'lifetime_conversion_cap': '0.00',
                'create_date_utc': '2016-08-26 09:59:29',
                'expiration_date': '2030-12-12 23:59:59',
                'use_revenue_groups': '0',
                'dne_download_url': None,
                'session_impression_hours': '24',
                'monthly_revenue_cap': '0.00',
                'require_approval': '0',
                'converted_offer_url': None,
                'email_instructions_from': None,
                'enable_offer_whitelist': '0',
                'default_goal_name': None,
                'has_goals_enabled': '0',
                'max_percent_payout': None,
                'target_browsers': '0',
                'is_seo_friendly_301': '0',
                'dne_list_id': None,
                'conversion_ratio_threshold': None,
                'use_payout_groups': '0',
                'enforce_geo_targeting': '0',
                'use_target_rules': '0',
                'payout_type': 'cpa_flat',
                'max_payout': '0.00000',
                'protocol': 'http',
                'monthly_payout_cap': '0.00',
                'preview_url': 'http://example.com',
                'tiered_payout': '0',
                'subscription_duration': None,
                'is_expired': '0',
                'disable_click_macro': '0',
                'modified': -62169966000,
                'email_instructions': '0',
                'currency': None,
                'lifetime_revenue_cap': '0.00',
                'status': 'pending',
                'conversion_cap': '0',
                'id': '148',
                'revenue_cap': '0.00',
                'approve_conversions': None,
                'website_links_copy_static_params': '0',
                'monthly_conversion_cap': '0',
                'allow_direct_links': '0',
                'terms_and_conditions': None,
                'featured': None,
                'note': '',
                'ref_id': None,
                'click_macro_url': None,
                'description': None,
                'rating': None,
                'set_session_on_impression': '0',
                'enforce_encrypt_tracking_pixels': '0',
                'email_instructions_subject': None,
                'enforce_secure_tracking_link': '0',
                'dne_unsubscribe_url': None,
                'allow_multiple_conversions': '0',
                'session_hours': '24',
                'tiered_revenue': '0',
                'offer_url': 'http://example.com',
                'converted_offer_type': '',
                'customer_list_id': None,
                'subscription_frequency': None,
                'is_private': '0',
                'is_subscription': '0',
                'revenue_type': 'cpa_flat',
                'allow_website_links': '0',
                'converted_offer_id': None,
                'advertiser_id': None,
                'require_terms_and_conditions': 0,
                'display_advertiser': '0',
                'name': 'Test',
                'redirect_offer_id': None,
                'dne_third_party_list': False
            }
        },
        'status': 1,
        'errorMessage': None,
        'errors': []
    },
    'request': {
        'NetworkToken': 'token',
        'Target': 'Offer',
        'NetworkId': 'id',
        'Version': '2',
        'data': {
            'expiration_date': '2030-12-12 23:59:59',
            'name': 'Test',
            'offer_url': 'http://example.com',
            'preview_url': 'http://example.com',
            'status': 'pending'
        },
        'Format': 'json',
        'Service': 'HasOffers',
        'Method': 'create'
    }
}

CREATE_OFFER_FAIL = {
    'response': {
        'errors': [{
            'publicMessage': 'Could not create offer.',
            'attribute_name': 'name',
            'err_msg': 'Name cannot be blank.',
            'err_code': 1
        }, {
            'attribute_name': 'preview_url',
            'err_msg': 'Preview_url cannot be blank.',
            'err_code': 1
        }, {
            'attribute_name': 'offer_url',
            'err_msg': 'Offer_url cannot be blank.',
            'err_code': 1
        }, {
            'attribute_name': 'expiration_date',
            'err_msg': 'Expiration_date cannot be blank.',
            'err_code': 1
        }],
        'httpStatus': 200,
        'data': '',
        'status': -1,
        'errorMessage': 'Could not create offer.'
    },
    'request': {
        'NetworkId': 'id',
        'Format': 'json',
        'Method': 'create',
        'NetworkToken': 'token',
        'Target': 'Offer',
        'Service': 'HasOffers',
        'data': {
            'status': 'pending',
            'protocol': 'server'
        },
        'Version': '2'
    }
}

FIND_BY_ID_OFFER_SUCCESS = {
    'response': {
        'httpStatus': 200,
        'data': {
            'Offer': {
                'hostname_id': None,
                'show_custom_variables': '0',
                'default_payout': '0.00000',
                'show_mail_list': '0',
                'payout_cap': '0.00',
                'percent_payout': None,
                'lifetime_payout_cap': '0.00',
                'lifetime_conversion_cap': '0.00',
                'create_date_utc': '2016-08-26 09:59:29',
                'expiration_date': '2030-12-12 23:59:59',
                'use_revenue_groups': '0',
                'dne_download_url': None,
                'session_impression_hours': '24',
                'monthly_revenue_cap': '0.00',
                'require_approval': '0',
                'converted_offer_url': None,
                'email_instructions_from': None,
                'enable_offer_whitelist': '0',
                'default_goal_name': None,
                'has_goals_enabled': '0',
                'max_percent_payout': None,
                'target_browsers': '0',
                'is_seo_friendly_301': '0',
                'dne_list_id': None,
                'conversion_ratio_threshold': None,
                'use_payout_groups': '0',
                'enforce_geo_targeting': '0',
                'use_target_rules': '0',
                'payout_type': 'cpa_flat',
                'max_payout': '0.00000',
                'protocol': 'http',
                'monthly_payout_cap': '0.00',
                'preview_url': 'http://example.com',
                'tiered_payout': '0',
                'subscription_duration': None,
                'is_expired': '0',
                'disable_click_macro': '0',
                'modified': -62169966000,
                'email_instructions': '0',
                'currency': None,
                'lifetime_revenue_cap': '0.00',
                'status': 'pending',
                'conversion_cap': '0',
                'id': '148',
                'revenue_cap': '0.00',
                'approve_conversions': None,
                'website_links_copy_static_params': '0',
                'monthly_conversion_cap': '0',
                'allow_direct_links': '0',
                'terms_and_conditions': None,
                'featured': None,
                'note': '',
                'ref_id': None,
                'click_macro_url': None,
                'description': None,
                'rating': None,
                'set_session_on_impression': '0',
                'enforce_encrypt_tracking_pixels': '0',
                'email_instructions_subject': None,
                'enforce_secure_tracking_link': '0',
                'dne_unsubscribe_url': None,
                'allow_multiple_conversions': '0',
                'session_hours': '24',
                'tiered_revenue': '0',
                'offer_url': 'http://example.com',
                'converted_offer_type': '',
                'customer_list_id': None,
                'subscription_frequency': None,
                'is_private': '0',
                'is_subscription': '0',
                'revenue_type': 'cpa_flat',
                'allow_website_links': '0',
                'converted_offer_id': None,
                'advertiser_id': None,
                'require_terms_and_conditions': 0,
                'display_advertiser': '0',
                'name': 'Test',
                'redirect_offer_id': None,
                'dne_third_party_list': False
            }
        },
        'status': 1,
        'errorMessage': None,
        'errors': []
    },
    'request': {
        'NetworkToken': 'token',
        'Target': 'Offer',
        'NetworkId': 'id',
        'id': '148',
        'Version': '2',
        'Format': 'json',
        'Service': 'HasOffers',
        'Method': 'findById'
    }
}

FIND_BY_ID_OFFER_FAIL = {
    'response': {
        'httpStatus': 200,
        'data': None,
        'status': 1,
        'errorMessage': None,
        'errors': []
    },
    'request': {
        'NetworkToken': 'token',
        'Target': 'Offer',
        'NetworkId': 'id',
        'id': '1000',
        'Version': '2',
        'Format': 'json',
        'Service': 'HasOffers',
        'Method': 'findById'
    }
}

UPDATE_OFFER_SUCCESS = {
    'response': {
        'data': {
            'Offer': {
                'converted_offer_type': '',
                'name': 'Test',
                'require_terms_and_conditions': 0,
                'subscription_frequency': None,
                'lifetime_payout_cap': '0.00',
                'payout_type': 'cpa_flat',
                'preview_url': 'http://example.com',
                'show_mail_list': '0',
                'currency': None,
                'display_advertiser': '0',
                'use_target_rules': '0',
                'enforce_encrypt_tracking_pixels': '0',
                'set_session_on_impression': '0',
                'is_expired': '0',
                'protocol': 'http',
                'max_payout': '0.00000',
                'dne_unsubscribe_url': None,
                'is_private': '0',
                'default_goal_name': None,
                'use_payout_groups': '0',
                'allow_direct_links': '0',
                'payout_cap': '0.00',
                'disable_click_macro': '0',
                'offer_url': 'http://test.com',
                'tiered_revenue': '0',
                'is_subscription': '0',
                'id': '1',
                'create_date_utc': '2016-08-26 09:59:29',
                'session_impression_hours': '24',
                'subscription_duration': None,
                'has_goals_enabled': '0',
                'allow_multiple_conversions': '0',
                'dne_download_url': None,
                'dne_list_id': None,
                'modified': -62169966000,
                'allow_website_links': '0',
                'click_macro_url': None,
                'featured': None,
                'advertiser_id': None,
                'default_payout': '0.00000',
                'rating': None,
                'session_hours': '24',
                'revenue_cap': '0.00',
                'description': None,
                'customer_list_id': None,
                'lifetime_revenue_cap': '0.00',
                'monthly_payout_cap': '0.00',
                'max_percent_payout': None,
                'note': '',
                'website_links_copy_static_params': '0',
                'monthly_revenue_cap': '0.00',
                'dne_third_party_list': False,
                'tiered_payout': '0',
                'converted_offer_url': None,
                'terms_and_conditions': None,
                'percent_payout': None,
                'enforce_secure_tracking_link': '0',
                'expiration_date': '2030-12-12 23:59:59',
                'approve_conversions': None,
                'lifetime_conversion_cap': '0.00',
                'status': 'pending',
                'conversion_cap': '0',
                'ref_id': None,
                'is_seo_friendly_301': '0',
                'converted_offer_id': None,
                'email_instructions_subject': None,
                'require_approval': '0',
                'redirect_offer_id': None,
                'enable_offer_whitelist': '0',
                'use_revenue_groups': '0',
                'email_instructions_from': None,
                'show_custom_variables': '0',
                'conversion_ratio_threshold': None,
                'email_instructions': '0',
                'revenue_type': 'cpa_flat',
                'hostname_id': None,
                'enforce_geo_targeting': '0',
                'target_browsers': '0',
                'monthly_conversion_cap': '0'
            }
        },
        'status': 1,
        'httpStatus': 200,
        'errorMessage': None,
        'errors': []
    },
    'request': {
        'id': '148',
        'Method': 'update',
        'Service': 'HasOffers',
        'data': {
            'use_target_rules': '0',
            'name': 'Test',
            'require_terms_and_conditions': '0',
            'payout_type': 'cpa_flat',
            'preview_url': 'http://example.com',
            'show_mail_list': '0',
            'show_custom_variables': '0',
            'display_advertiser': '0',
            'is_expired': '0',
            'protocol': 'http',
            'session_hours': '24',
            'is_private': '0',
            'use_payout_groups': '0',
            'payout_cap': '0.00',
            'disable_click_macro': '0',
            'offer_url': 'http://test.com',
            'tiered_revenue': '0',
            'is_subscription': '0',
            'create_date_utc': '2016-08-26 09:59:29',
            'set_session_on_impression': '0',
            'has_goals_enabled': '0',
            'allow_multiple_conversions': '0',
            'allow_website_links': '0',
            'lifetime_payout_cap': '0.00',
            'default_payout': '0.00000',
            'revenue_type': 'cpa_flat',
            'enforce_encrypt_tracking_pixels': '0',
            'revenue_cap': '0.00',
            'status': 'pending',
            'lifetime_revenue_cap': '0.00',
            'monthly_payout_cap': '0.00',
            'note': '',
            'website_links_copy_static_params': '0',
            'monthly_revenue_cap': '0.00',
            'max_payout': '0.00000',
            'tiered_payout': '0',
            'allow_direct_links': '0',
            'enforce_secure_tracking_link': '0',
            'expiration_date': '2030-12-12 23:59:59',
            'lifetime_conversion_cap': '0.00',
            'modified': '-62169966000',
            'conversion_cap': '0',
            'is_seo_friendly_301': '0',
            'email_instructions': '0',
            'enforce_geo_targeting': '0',
            'require_approval': '0',
            'use_revenue_groups': '0',
            'converted_offer_type': '',
            'session_impression_hours': '24',
            'enable_offer_whitelist': '0',
            'target_browsers': '0',
            'monthly_conversion_cap': '0'
        },
        'Format': 'json',
        'Target': 'Offer',
        'NetworkId': 'id',
        'Version': '2',
        'NetworkToken': 'token'
    }
}

ADD_TARGET_COUNTRY_SUCCESS = {
    'response': {
        'errorMessage': None,
        'status': 1,
        'data': True,
        'httpStatus': 200,
        'errors': []
    },
    'request': {
        'id': '148',
        'Format': 'json',
        'NetworkId': 'id',
        'NetworkToken': 'token',
        'Target': 'Offer',
        'Version': '2',
        'country_code': 'ES',
        'Method': 'addTargetCountry',
        'Service': 'HasOffers'
    }
}

ADD_CATEGORY_SUCCESS = {
    'request': {
        'Version': '2',
        'id': '148',
        'Service': 'HasOffers',
        'category_id': '1',
        'Format': 'json',
        'NetworkId': 'id',
        'Target': 'Offer',
        'Method': 'addCategory',
        'NetworkToken': 'token'
        },
    'response': {
        'httpStatus': 200,
        'errors': [],
        'data': True,
        'status': 1,
        'errorMessage': None
        }
    }
ADD_CATEGORY_FAIL = {
    'request': {
        'Version': '2',
        'id': '148',
        'Service': 'HasOffers',
        'category_id': '-1',
        'Format': 'json',
        'NetworkId': 'id',
        'Target': 'Offer',
        'Method': 'addCategory',
        'NetworkToken': 'token'
        },
    'response': {
        'httpStatus': 200,
        'errors': [{
                       'publicMessage': 'Row id is negative'
                       }],
        'data': '',
        'status': -1,
        'errorMessage': 'Row id is negative'
        }
    }
